### ISSUE TITLE
Will you update the copr repo?

### ISSUE THREAD

**Issue by AshtakaOOf** [mjakeman/s76-scheduler-plugin#3]
There is a new version of system76 scheduler out.
And the copr repo wasn't updated, are you still working on this extension and the copr repo?

**Comment by KyleGospo** [comment]
I forked this to make a bleeding edge version, you're welcome to use my fork and mjakeman's gnome extension in the meantime.

**Comment by mjakeman** [comment]
Hi, I'm definitely still working on this. Unfortunately I've injured my arm so all my projects are on the backburner for the mean time. 

I've rewritten the fedora package file and pushed an update to the COPR with version 1.2.1 from upstream. Can you verify if it works for you?
