### ISSUE TITLE
failed to set value

### ISSUE THREAD

**Issue by traek728** [mjakeman/s76-scheduler-plugin#4]
I'm not sure if this is an issue or not, just something I noticed when starting the com.system76.Scheduler.service on Fedora 36.  When the service is started on Fedora 36, I am receiving the log messages below showing that it fails to set certain values which do not seem to exist:

● com.system76.Scheduler.service - Automatically configure CPU scheduler for responsiveness on AC
     Loaded: loaded (/usr/lib/systemd/system/com.system76.Scheduler.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2022-05-30 12:38:56 EDT; 28s ago
   Main PID: 1766 (system76-schedu)
      Tasks: 3 (limit: 18846)
     Memory: 8.8M
        CPU: 30ms
     CGroup: /system.slice/com.system76.Scheduler.service
             └─ 1766 /usr/bin/system76-scheduler daemon

May 30 12:38:56  system76-scheduler[1766]:         (Assignment(CpuPriority(-11), Realtime(PriorityLevel(0))), {"pipewire", "pipewire-pulse", "wireplumber"})
May 30 12:38:56  system76-scheduler[1766]:         (Assignment(CpuPriority(-9), BestEffort(PriorityLevel(0))), {"easyeffects"})
May 30 12:38:56  system76-scheduler[1766]:         (Assignment(CpuPriority(-5), BestEffort(PriorityLevel(4))), {"Xorg", "amsynth", "gnome-shell", "kwin", "steam", "sway", "vrcompositor", "vrdashboard", "vrmonitor", "vrserver"})
May 30 12:38:56  system76-scheduler[1766]:         (Assignment(CpuPriority(0), Standard), {"dbus", "sshd", "systemd"})
May 30 12:38:56  system76-scheduler[1766]:         (Assignment(CpuPriority(9), Idle), {"ModemManager", "NetworkManager", "accounts-daemon", "acpid", "automount", "avahi-daemon", "bluetoothd", "colord", "cron", "cups-browsed", "cup>
May 30 12:38:56  system76-scheduler[1766]:         (Assignment(CpuPriority(19), Idle), {"FAHClient", "FAHCoreWrapper", "apt", "apt-get", "boinc", "c++", "cargo", "clang", "cpp", "dpkg", "flatpak", "fossilize_replay", "g++", "gcc",>
May 30 12:38:56  system76-scheduler[1766]: failed to set value in /sys/kernel/debug/sched/latency_ns: Operation not permitted (os error 1)
May 30 12:38:56  system76-scheduler[1766]: failed to set value in /sys/kernel/debug/sched/min_granularity_ns: Operation not permitted (os error 1)
May 30 12:38:56  system76-scheduler[1766]: failed to set value in /sys/kernel/debug/sched/wakeup_granularity_ns: Operation not permitted (os error 1)
May 30 12:38:56  system76-scheduler[1766]: failed to set value in /sys/kernel/debug/sched/preempt: Operation not permitted (os error 1)

**Comment by KyleGospo** [comment]
Secure boot prevents access to values under debug. Disable it and this will work. Unfortunately I know no other workaround.

**Comment by traek728** [comment]
Ah, that makes sense.  Thank you!
